name: melbourne-house-price-analysis
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - seaborn
      - matplotlib
      - scikit-learn
      - xgboost
      - shap
      - streamlit
      - joblib
      - jupyter
